---
# tasks file for check.ACup
- name: to check if ac is up or not
  shell:  curl -k https://{{ item }}:8443/nps/servlet/portal | grep '<title>.*</title>' > /ac.txt
  with_inventory_hostnames: AC
  register: curlres

- name: to check the file
  shell: cat /ac.txt | grep -i  acc | wc -l
  register: count

- name: to remove the file
  shell: rm -r /ac.txt

- name: exit if ac is not up
  fail: msg="AC is not up and running"
  when: count.stdout_lines == 0

