---
# tasks file for idp.install

- name: Enable EPEL Repository on CentOS 7
  yum:
    name: epel-release
    state: latest
  become: True
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Verificar que los prerequisitos se encuentren instalados
  yum:
    name:
      - python-pip
      - bind-utils
      - rsyslog
      - rsyslog-gnutls
      - ncurses-libs
      - ncurses-libs.i686
      - unzip
      - ntp
      - net-tools
      - zip
      - net-snmp
    state: latest
    update_cache: true
  become: yes

- name: Instalar pexpect
  pip:
    name:
      - pexpect>3.3
      - pip
  become: yes

- name: Crear un directorio de instalación en remoto
  file:
    path: /installer/NAM
    state: directory
  become: yes

- name: Extraer instalador (local) en remoto
  become: yes
  unarchive:
    src: "../../../installers/{{ac_idp_installer}}"
    dest: /installer/NAM
    creates: /installer/NAM/novell-access-manager-4.5.0.0-190

- shell: ls -d /installer/NAM/novell-access-manager-*
  register: dir_name
  become: yes

# Es necesario para RHEL según
# https://support.microfocus.com/kb/doc.php?id=7017418
- name: Comentar  chequeo NTP en script de preinstalación
  copy:
    src: files/pre_install.sh
    dest: "{{ dir_name.stdout }}/scripts/pre_install.sh"
    owner: root
    group: root
    mode: "0755"
    backup: yes
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Quitar chequeo ntp - nam_rhel7_functions
  copy:
    src: files/nam_rhel7_functions.sh
    dest: "{{ dir_name.stdout }}/scripts/nam_rhel7_functions.sh"
    owner: root
    group: root
    mode: "0755"
    backup: yes
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

# debe coincidir con la IP de Vagrantfile
- name: Agregar IP  en /etc/hosts
  lineinfile:
    path: /etc/hosts
    state: present
    line: |
      {{ids_ip_address}}     {{ids_fqdn}}
      {{ag_ip_address}}     {{ag_fqdn}}
      {{ac_ip_address}}     {{ac_fqdn}}
    owner: root
    group: root
    mode: "0644"
  become: yes

# engañar al instalador para que no se queje por la versión
- name: Agregar release en /etc/redhat-release
  lineinfile:
    path: /etc/redhat-release
    state: present
    line: Red Hat Enterprise Linux Server release 7.5 (Maipo)
    insertbefore: CentOS Linux release 7\.(.*)
    owner: root
    group: root
    mode: "0644"
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Registrar directorio de instalación en una variable
  shell: ls -d /installer/NAM/novell-access-manager-*
  register: dir_name
  become: yes

- name: Ejecutar instalador
  args:
    chdir: "{{ dir_name.stdout }}"
  become: yes
  expect:
    creates: /opt/novell/nam/idp/bin/novell-idp
    command: ./install.sh
    echo: yes
    timeout: 1500
    responses:
      (.*)Would you like to continue(.*): "y"
      (.*)Select installation(.*): "2"
      (.*)PRESS ENTER TO CONTINUE(.*): "\n"
      (.*)DO YOU ACCEPT THE TERMS OF THIS LICENSE AGREEMENT(.*): "y"
      (.*)Would you like to continue with the installation(.*): "y"
      \[\](.*): "{{ac_ip_address}}"
      (.*)Enter the Access Manager Administration user ID(.*): "{{ids_admin_user}}"
      (.*)Enter the Access Manager Administration password(.*): "{{ids_admin_password}}"
      \[\d+\.\d+\.\d+.\d+\](.*): "{{ids_ip_address}}"
      (.*)Re-enter the password for verification(.*): "{{ids_admin_password}}"
      (.*)Is local NAT available for the Identity Server(.*): "n"
