---
- name: Verificar las versiones instaladas
  yum:
    name:
      - netiq-tomcat
      - netiq-jrex
      - novell-imanager
      - novell-devman
      - novell-edirectory-xdasinstrument
    state: present
  register: paquetes
  become: yes
