---
# tasks file for ac.install
- name: Verificar que los prerequisitos se encuentren instalados
  yum:
    name:
      - bind-utils
      - python-pip
      - rsyslog
      - rsyslog-gnutls
      - ncurses-libs
      - ncurses-libs.i686
      - unzip
      - ntp
      - net-tools
      - zip
      - net-snmp
    state: latest
    update_cache: true
  become: yes

- name: Extraer instalador (local) en remoto
  become: yes
  unarchive:
    src: ../../../installers/am-45-access-manager-lin64.tar.gz
    dest: /installer/NAM
    creates: /installer/NAM/novell-access-manager-4.5.0.0-190
  register: installer_path

- name: Registrar directorio de instalación en una variable
  shell: ls -d /installer/NAM/novell-access-manager-*
  register: dir_name
  become: yes

- debug:
    var: installer_path.files[0]
# Es necesario para RHEL según
# https://support.microfocus.com/kb/doc.php?id=7017418
- name: Comentar  chequeo NTP en script de preinstalación
  copy:
    src: files/pre_install.sh
    dest: "{{ dir_name.stdout }}/scripts/pre_install.sh"
    owner: root
    group: root
    mode: "0755"
    backup: yes
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Quitar chequeo ntp - nam_rhel7_functions
  copy:
    src: files/nam_rhel7_functions.sh
    dest: "{{ dir_name.stdout }}/scripts/nam_rhel7_functions.sh"
    owner: root
    group: root
    mode: "0755"
    backup: yes
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

# Para que funcione es necesario que pexpect se encuentre en el remoto
# sudo pip -E pexpect
- name: Ejecutar instalador
  args:
    chdir: "{{ dir_name.stdout }}"
  become: yes
  expect:
    command: ./install.sh
    echo: yes
    timeout: 1500
    responses:
      (.*)Would you like to continue(.*): "y"
      (.*)Select installation(.*): "1"
      (.*)PRESS ENTER TO CONTINUE(.*): "\n"
      (.*)DO YOU ACCEPT THE TERMS OF THIS LICENSE AGREEMENT(.*): "y"
      (.*)Would you like to continue with the installation(.*): "y"
      (.*)Is this the primary administration server in a failover group(.*): "y"
      (.*)Enter the Access Manager Administration user ID(.*): "admin"
      (.*)Enter the Access Manager Administration password(.*): "{{ac_admin_password}}"
      (.*)Re-enter the password for verification(.*): "{{ac_admin_password}}"
      \[\](.*): "{{ac_ip_address}}"
      \[\d+\.\d+\.\d+.\d+\](.*): "{{ac_ip_address}}"

- debug:
    var: run_installation
