---
# tasks file for ag.install
- name: Verificar que los prerequisitos se encuentren instalados
  yum:
    name:
      - apr
      - apr-util
      - unixODBC
      - libesmtp
      - pcre
      - patch
      - psmisc
      - libtool-ltdl
      - nss-softokn-freebl.i686
      - ncurses-libs
      - ncurses-libs.i686
    state: latest
  become: yes

- name: Extraer instalador (local) en remoto
  become: yes
  unarchive:
    src: ../../../installers/am-45-access-gw-lin64.tar.gz
    dest: /installer/NAM
    creates: /installer/NAM/novell-access-gateway-4.5.0.0-190
  register: installer_path

- shell: ls -d /installer/NAM/novell* | head -1
  register: dir_name
  become: yes

- name: Ejecutar instalador
  args:
    chdir: "{{ dir_name.stdout }}"
  become: yes
  expect:
    creates: /opt/novell/nam/idp/bin/novell-idp
    command: ./ag_install.sh
    echo: yes
    timeout: 1500
    responses:
      (.*)Would you like to continue(.*): "y"
      (.*)Select installation(.*): "2"
      (.*)PRESS ENTER TO CONTINUE(.*): "\n"
      (.*)DO YOU ACCEPT THE TERMS OF THIS LICENSE AGREEMENT(.*): "y"
      (.*)Would you like to continue with the installation(.*): "y"
      \[\](.*): "{{ac_ip_address}}"
      (.*)Enter the Access Manager Administration user ID(.*): "{{ids_admin_user}}"
      (.*)Enter the Access Manager Administration password(.*): "{{ids_admin_password}}"
      \[\d+\.\d+\.\d+.\d+\](.*): "{{ag_ip_address}}"
      (.*)Re-enter the password for verification(.*): "{{ids_admin_password}}"
      (.*)Is local NAT available for the Access Gateway(.*): "n"
