---
- hosts: ac
  roles:
    - all.checkPrerequisites
    - ac.install
    - ac.checkSoftwareVersion
    - ac.checkWebConsoleIsUp
  vars_files:
    - ../variables.yml

- hosts: idp
  roles:
    - all.checkPrerequisites
    - idp.install
    - idp.checkSoftwareVersion
    - idp.checkWebConsoleIsUp
  vars_files:
    - ../variables.yml

- hosts: ag
  roles:
    - all.checkPrerequisites
    - ag.install
    - ag.checkSoftwareVersion
  vars_files:
    - ../variables.yml
