---
- hosts: ac
  roles:
    - all.checkPrerequisites
    - ac.install
    - ac.checkSoftwareVersion
  vars_files:
    - ../variables.yml

- hosts: idp
  roles:
    - all.checkPrerequisites
    - idp.install
    - idp.checkSoftwareVersion
  vars_files:
    - ../variables.yml

- hosts: ag
  roles:
    - all.checkPrerequisites
    - ag.install
    - ag.checkSoftwareVersion
  vars_files:
    - ../variables.yml

- hosts: ac,idp,ag
  roles:
    - system.reboot

- hosts: ac, idp, ag
  tags: health-check
  roles:
    - role: check.WebUp
  vars_files:
    - ../variables.yml
